// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALxJESfNPutrTgta9OKmMWxZDFjtgQOcM',
    appId: '1:145419134447:web:4a6d200fc01400afbb821a',
    messagingSenderId: '145419134447',
    projectId: 'curvy-4e1ae',
    authDomain: 'curvy-4e1ae.firebaseapp.com',
    storageBucket: 'curvy-4e1ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBellP6cyIhkjsJshsUlPTAHI6oBwWkxd4',
    appId: '1:145419134447:android:6c2126cb7e7300dabb821a',
    messagingSenderId: '145419134447',
    projectId: 'curvy-4e1ae',
    storageBucket: 'curvy-4e1ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCakU4iVqA_ITdr1cxqxE3y5qb9GBDNR10',
    appId: '1:145419134447:ios:c8ff3c2b0ba63dabbb821a',
    messagingSenderId: '145419134447',
    projectId: 'curvy-4e1ae',
    storageBucket: 'curvy-4e1ae.appspot.com',
    androidClientId: '145419134447-h19rjc2vipa3mhokjsflnh1c7ssom6d3.apps.googleusercontent.com',
    iosClientId: '145419134447-ptk3pepdqc6lcieo3pv88rbi60gf9tfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.curvyApp',
  );
}
